---
- name: Copy the memcached_exporter systemd service file
  template:
    src: memcached_exporter.service.j2
    dest: /etc/systemd/system/memcached_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart memcached_exporter

- block:
    - name: Create memcached_exporter config directory
      file:
        path: "/etc/memcached_exporter"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy the memcached_exporter config file
      template:
        src: config.yaml.j2
        dest: /etc/memcached_exporter/config.yaml
        owner: root
        group: root
        mode: 0644
      notify: restart memcached_exporter
  when:
    ( memcached_exporter_tls_server_config | length > 0 ) or
    ( memcached_exporter_http_server_config | length > 0 ) or
    ( memcached_exporter_basic_auth_users | length > 0 )

- name: Create textfile collector dir
  file:
    path: "{{ memcached_exporter_textfile_dir }}"
    state: directory
    owner: "{{ _memcached_exporter_system_user }}"
    group: "{{ _memcached_exporter_system_group }}"
    recurse: true
    mode: u+rwX,g+rwX,o=rX
  when: memcached_exporter_textfile_dir | length > 0
