---
- name: Create the memcached_exporter group
  group:
    name: "{{ _memcached_exporter_system_group }}"
    state: present
    system: true
  when: _memcached_exporter_system_group != "root"

- name: Create the memcached_exporter user
  user:
    name: "{{ _memcached_exporter_system_user }}"
    groups: "{{ _memcached_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when: _memcached_exporter_system_user != "root"

- block:
    - name: Download memcached_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus/memcached_exporter/releases/download/v{{ memcached_exporter_version }}/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ memcached_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack memcached_exporter binary
      become: false
      unarchive:
        src: "/tmp/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}/memcached_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate memcached_exporter binaries
      copy:
        src: "/tmp/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}/memcached_exporter"
        dest: "{{ _memcached_exporter_binary_install_dir }}/memcached_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart memcached_exporter
      when: not ansible_check_mode
  when: memcached_exporter_binary_local_dir | length == 0

- name: propagate locally distributed memcached_exporter binary
  copy:
    src: "{{ memcached_exporter_binary_local_dir }}/memcached_exporter"
    dest: "{{ _memcached_exporter_binary_install_dir }}/memcached_exporter"
    mode: 0755
    owner: root
    group: root
  when: memcached_exporter_binary_local_dir | length > 0
  notify: restart memcached_exporter
